apiVersion: v1
kind: Service
metadata:
  name: mynginxservice
spec:
   #matchLabels are not supported by Service (https://medium.com/@zwhitchcox/matchlabels-labels-and-selectors-explained-in-detail-for-beginners-d421bdd05362)
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080